import Darwin
import Foundation

public struct InvocationReceipt: Codable, Equatable, Sendable {
  public struct Provenance: Codable, Equatable, Sendable {
    public let bepPath: String
  }

  public let bazelrcs: [String]
  public let command: String
  public let commandOptions: [String]
  public let environmentKeys: [String]
  public let labels: [String]
  public let materialization: [String: String]
  public let modes: [String: String]
  public let outputGroups: [String]
  public let provenance: Provenance
  public let schemaVersion: Int
  public let startupOptions: [String]
  public let targetIDs: [String]
  public let targets: [String]
  public let workingDirectory: String
}

public enum InvocationReceiptError: LocalizedError, Equatable, Sendable {
  case bindingMismatch(String)
  case credentialShapedContent(String)
  case invalidContract(String)
  case invalidJSON(String)
  case invalidShape(String)
  case unsafeFile(String)
  case unsupportedSchema(Int)

  public var errorDescription: String? {
    switch self {
    case .bindingMismatch(let field):
      return "The invocation receipt does not match the prepared \(field)."
    case .credentialShapedContent(let field):
      return "The invocation receipt contains credential-shaped content in \(field)."
    case .invalidContract(let description):
      return "The invocation receipt violates schema v1: \(description)"
    case .invalidJSON(let description):
      return "The invocation receipt is not valid JSON: \(description)"
    case .invalidShape(let description):
      return "The invocation receipt has an invalid shape: \(description)"
    case .unsafeFile(let path):
      return
        "The invocation receipt is missing, linked, oversized, or has unsafe permissions: \(path)"
    case .unsupportedSchema(let version):
      return "Unsupported invocation receipt schema version \(version)."
    }
  }
}

public enum InvocationReceiptValidator {
  private static let maximumReceiptBytes = 4 * 1024 * 1024
  private static let maximumRequestBytes = 1024 * 1024

  /// Environment keys generated by the checked-in rules_xcodeproj Bazel adapter itself rather
  /// than selected from Xcode settings or inherited from the restricted process environment.
  /// The three `SWIFTBUILD_BAZEL_PROXY_*` controls are intentionally absent: they configure the
  /// adapter parent process and are not members of the sanitized Bazel child environment recorded
  /// by schema-v1 receipts.
  public static let generatedEnvironmentKeys: Set<String> = [
    "BAZELISK_SKIP_WRAPPER", "BAZEL_REAL", "BUILD_WORKSPACE_DIRECTORY", "LANG",
  ]

  public static func loadAndValidate(
    for plan: ResolvedBuildPlan,
    invocation: AdapterInvocation,
    fileManager: FileManager = .default
  ) throws -> InvocationReceipt {
    let data = try readSecureReceipt(invocation.receiptURL, fileManager: fileManager)
    try validateShape(data)

    let receipt: InvocationReceipt
    do {
      receipt = try JSONDecoder().decode(InvocationReceipt.self, from: data)
    } catch {
      throw InvocationReceiptError.invalidJSON(error.localizedDescription)
    }
    guard receipt.schemaVersion == plan.manifest.invocation.receiptSchemaVersion,
      receipt.schemaVersion == 1
    else {
      throw InvocationReceiptError.unsupportedSchema(receipt.schemaVersion)
    }

    guard receipt.command == "build",
      receipt.targets == [plan.manifest.invocation.generatorLabel]
    else {
      throw InvocationReceiptError.invalidContract(
        "command and generated target must match the manifest"
      )
    }
    guard receipt.workingDirectory.hasPrefix("/"),
      !BuildProxySecurity.hasControlCharacters(receipt.workingDirectory),
      URL(fileURLWithPath: receipt.workingDirectory).resolvingSymlinksInPath().standardizedFileURL
        == invocation.workingDirectoryURL.resolvingSymlinksInPath().standardizedFileURL
    else {
      throw InvocationReceiptError.bindingMismatch("working directory")
    }
    guard receipt.provenance.bepPath.hasPrefix("/"),
      !BuildProxySecurity.hasControlCharacters(receipt.provenance.bepPath),
      URL(fileURLWithPath: receipt.provenance.bepPath).standardizedFileURL
        == invocation.bepURL.standardizedFileURL
    else {
      throw InvocationReceiptError.bindingMismatch("BEP output")
    }
    guard receipt.materialization == ["contract": "manifest-v2"] else {
      throw InvocationReceiptError.bindingMismatch("materialization contract")
    }

    let requestLabels = try readRequest(
      "labels",
      from: invocation.requestDirectoryURL,
      fileManager: fileManager
    )
    let requestTargetIDs = try readRequest(
      "target_ids",
      from: invocation.requestDirectoryURL,
      fileManager: fileManager
    )
    let requestOutputGroups = try readRequest(
      "output_groups",
      from: invocation.requestDirectoryURL,
      fileManager: fileManager
    )
    guard requestLabels == normalized(plan.adapterRequest.labels),
      requestTargetIDs == normalized(plan.adapterRequest.targetIDs),
      requestOutputGroups == normalized(plan.adapterRequest.outputGroups)
    else {
      throw InvocationReceiptError.bindingMismatch("request files")
    }
    guard receipt.labels == requestLabels else {
      throw InvocationReceiptError.bindingMismatch("labels")
    }
    guard receipt.targetIDs == requestTargetIDs else {
      throw InvocationReceiptError.bindingMismatch("target IDs")
    }
    guard Set(requestOutputGroups).isSubset(of: Set(receipt.outputGroups)) else {
      throw InvocationReceiptError.bindingMismatch("output groups")
    }

    let planLabels = normalized(plan.targets.map(\.mapping.bazelLabel))
    let planTargetIDs = normalized(plan.targets.map(\.mapping.targetID))
    guard requestLabels == planLabels, requestTargetIDs == planTargetIDs else {
      throw InvocationReceiptError.bindingMismatch("resolved targets")
    }

    try validateOrderedStrings(receipt.startupOptions, field: "startupOptions")
    try validateOrderedStrings(receipt.bazelrcs, field: "bazelrcs")
    try validateOrderedStrings(receipt.commandOptions, field: "commandOptions")
    try validateSortedSet(receipt.targets, field: "targets")
    try validateSortedSet(receipt.labels, field: "labels")
    try validateSortedSet(receipt.outputGroups, field: "outputGroups")
    try validateSortedSet(receipt.targetIDs, field: "targetIDs")
    try validateEnvironmentKeys(receipt.environmentKeys, plan: plan)
    try validateDictionary(receipt.modes, field: "modes")
    try validateDictionary(receipt.materialization, field: "materialization")
    try validateModes(receipt.modes, plan: plan)
    return receipt
  }

  private static func readSecureReceipt(
    _ url: URL,
    fileManager: FileManager
  ) throws -> Data {
    do {
      return try securelyReadRegularFile(
        url,
        maximumBytes: maximumReceiptBytes,
        requirePrivatePermissions: true
      )
    } catch {
      throw InvocationReceiptError.unsafeFile(url.path)
    }
  }

  private static func validateShape(_ data: Data) throws {
    let value: Any
    do {
      value = try JSONSerialization.jsonObject(with: data)
    } catch {
      throw InvocationReceiptError.invalidJSON(error.localizedDescription)
    }
    let top = try object(
      value,
      path: "$",
      keys: [
        "bazelrcs", "command", "commandOptions", "environmentKeys", "labels",
        "materialization", "modes", "outputGroups", "provenance", "schemaVersion",
        "startupOptions", "targetIDs", "targets", "workingDirectory",
      ]
    )
    _ = try object(top["provenance"], path: "$.provenance", keys: ["bepPath"])
  }

  private static func object(
    _ value: Any?,
    path: String,
    keys: Set<String>
  ) throws -> [String: Any] {
    guard let object = value as? [String: Any] else {
      throw InvocationReceiptError.invalidShape("\(path) must be an object")
    }
    let actualKeys = Set(object.keys)
    guard actualKeys == keys else {
      let missing = keys.subtracting(actualKeys).sorted().joined(separator: ", ")
      let unknown = actualKeys.subtracting(keys).sorted().joined(separator: ", ")
      throw InvocationReceiptError.invalidShape(
        "\(path) key mismatch; missing [\(missing)], unknown [\(unknown)]"
      )
    }
    return object
  }

  private static func readRequest(
    _ name: String,
    from directory: URL,
    fileManager: FileManager
  ) throws -> [String] {
    let url = directory.appendingPathComponent(name)
    let data: Data
    do {
      data = try securelyReadRegularFile(
        url,
        maximumBytes: maximumRequestBytes,
        requirePrivatePermissions: true
      )
    } catch {
      throw InvocationReceiptError.bindingMismatch("\(name) request file")
    }
    guard let contents = String(data: data, encoding: .utf8),
      contents.hasSuffix("\n")
    else {
      throw InvocationReceiptError.bindingMismatch("\(name) request file")
    }
    if contents == "\n" {
      return []
    }
    let values = contents.split(separator: "\n", omittingEmptySubsequences: false).dropLast().map(
      String.init
    )
    guard !values.contains(""), values == normalized(values) else {
      throw InvocationReceiptError.bindingMismatch("\(name) request file")
    }
    return values
  }

  private static func validateOrderedStrings(_ values: [String], field: String) throws {
    for value in values {
      try validateSafeText(value, field: field)
    }
  }

  private static func validateSortedSet(_ values: [String], field: String) throws {
    guard values == normalized(values) else {
      throw InvocationReceiptError.invalidContract("\(field) must be sorted and unique")
    }
    try validateOrderedStrings(values, field: field)
  }

  private static func validateEnvironmentKeys(
    _ values: [String],
    plan: ResolvedBuildPlan
  ) throws {
    guard values == normalized(values) else {
      throw InvocationReceiptError.invalidContract(
        "environmentKeys must be sorted and unique"
      )
    }
    for key in values {
      guard BuildProxySecurity.isEnvironmentKey(key) else {
        throw InvocationReceiptError.invalidContract("invalid environment key \(key)")
      }
      if BuildProxySecurity.isSensitiveEnvironmentKey(key) {
        throw InvocationReceiptError.credentialShapedContent("environmentKeys")
      }
    }
    // The generated adapter records only names, and may omit manifest-declared Xcode settings
    // that were unset. Subset validation is therefore deliberate; widening beyond these three
    // explicit sources is not.
    let allowed = Set(plan.manifest.invocation.environmentKeys)
      .union(AdapterInvocationFactory.systemEnvironmentAllowlist)
      .union(generatedEnvironmentKeys)
    guard Set(values).isSubset(of: allowed) else {
      throw InvocationReceiptError.bindingMismatch("environment keys")
    }
  }

  private static func securelyReadRegularFile(
    _ url: URL,
    maximumBytes: Int,
    requirePrivatePermissions: Bool
  ) throws -> Data {
    guard url.isFileURL, url.path.hasPrefix("/"), maximumBytes >= 0 else {
      throw CocoaError(.fileReadInvalidFileName)
    }
    let descriptor = url.withUnsafeFileSystemRepresentation { path -> Int32 in
      guard let path else { return -1 }
      return Darwin.open(path, O_RDONLY | O_CLOEXEC | O_NOFOLLOW)
    }
    guard descriptor >= 0 else { throw CocoaError(.fileReadNoSuchFile) }
    defer { Darwin.close(descriptor) }

    var status = stat()
    guard Darwin.fstat(descriptor, &status) == 0,
      status.st_mode & S_IFMT == S_IFREG,
      status.st_size >= 0,
      status.st_size <= maximumBytes,
      !requirePrivatePermissions || status.st_mode & 0o077 == 0
    else {
      throw CocoaError(.fileReadUnknown)
    }

    var data = Data()
    data.reserveCapacity(Int(status.st_size))
    var buffer = [UInt8](repeating: 0, count: min(64 * 1024, maximumBytes + 1))
    while true {
      let count = Darwin.read(descriptor, &buffer, buffer.count)
      if count == 0 { break }
      if count < 0 {
        if errno == EINTR { continue }
        throw CocoaError(.fileReadUnknown)
      }
      guard count <= maximumBytes - data.count else {
        throw CocoaError(.fileReadTooLarge)
      }
      data.append(contentsOf: buffer.prefix(count))
    }
    return data
  }

  private static func validateDictionary(
    _ values: [String: String],
    field: String
  ) throws {
    guard !values.isEmpty else {
      throw InvocationReceiptError.invalidContract("\(field) must not be empty")
    }
    for (key, value) in values {
      guard BuildProxySecurity.isEnvironmentKey(key) else {
        throw InvocationReceiptError.invalidContract("\(field) contains invalid key \(key)")
      }
      try validateSafeText(value, field: field)
    }
  }

  private static func validateModes(
    _ modes: [String: String],
    plan: ResolvedBuildPlan
  ) throws {
    guard Set(modes.keys) == Set(["action", "config", "coverage", "previews"]),
      let expectedAction = plan.evaluatedEnvironment["ACTION"],
      modes["action"] == expectedAction,
      modes["coverage"] == (plan.evaluatedEnvironment["CLANG_COVERAGE_MAPPING"] ?? "NO"),
      modes["previews"] == (plan.evaluatedEnvironment["ENABLE_PREVIEWS"] ?? "NO")
    else {
      throw InvocationReceiptError.bindingMismatch("build modes")
    }
  }

  private static func validateSafeText(_ value: String, field: String) throws {
    guard !value.isEmpty, !BuildProxySecurity.hasControlCharacters(value) else {
      throw InvocationReceiptError.invalidContract("\(field) contains an empty or unsafe value")
    }
    if BuildProxySecurity.containsSensitiveEnvironmentValue(value) {
      throw InvocationReceiptError.credentialShapedContent(field)
    }
  }

  private static func normalized(_ values: [String]) -> [String] {
    Array(Set(values)).sorted()
  }
}
